// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfn6Zz9A8WuMsyaWQ3U4iBbM1L1f-oLP0',
    appId: '1:666235006734:web:41a3dcba58e03e118a315f',
    messagingSenderId: '666235006734',
    projectId: 'khapa-shapa-7f2b2',
    authDomain: 'khapa-shapa-7f2b2.firebaseapp.com',
    storageBucket: 'khapa-shapa-7f2b2.appspot.com',
    measurementId: 'G-8VKN29D0HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtqSIQHciZXAuhHKrTRNWqKxIT9EVGaeU',
    appId: '1:666235006734:android:6be051595a3c5d668a315f',
    messagingSenderId: '666235006734',
    projectId: 'khapa-shapa-7f2b2',
    storageBucket: 'khapa-shapa-7f2b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZBIIyIUqhIRezDYN5OrxncAmvtBJUys4',
    appId: '1:666235006734:ios:962dac9e0bbf16fe8a315f',
    messagingSenderId: '666235006734',
    projectId: 'khapa-shapa-7f2b2',
    storageBucket: 'khapa-shapa-7f2b2.appspot.com',
    iosClientId: '666235006734-j0h2b5c1jm43q6j5mfmi1jgnohscseug.apps.googleusercontent.com',
    iosBundleId: 'com.appbymuk.khapaShapa',
  );
}
